service:
  name: discord-lambda
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-offline-scheduler

provider:
  name: aws
  runtime: nodejs10.x

functions:
  cron:
    handler: src/handler.postMessage
    events:
      - schedule: rate(3 minutes)

# package:
#   exclude:
#     - node_modules/**/*
#   include:
#     handler.ts
