service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-offline
  - serverless-offline-scheduler

package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts

functions:
  postMessage:
    handler: handler.postMessage
    events:
      - schedule: rate(1 minute)